---@mod rocks.types
--
-- Copyright (C) 2023 Neorocks Org.
--
-- Version:    0.1.0
-- License:    GPLv3
-- Created:    05 Jul 2023
-- Updated:    27 Aug 2023
-- Homepage:   https://github.com/nvim-neorocks/rocks.nvim
-- Maintainers: NTBBloodbath <bloodbathalchemist@protonmail.com>, Vhyrro <vhyrro@gmail.com>
--
---@brief [[
--
-- rocks.nvim type definitions.
--
---@brief ]]

---@class (exact) RocksOptions
---@field rocks_path? string Local path in your filesystem to install rocks
---@field config_path? string Rocks declaration file path

--- types.lua ends here
