local fs = require("rocks.fs")
local tempdir = vim.fn.tempname()
describe("rocks.fs", function()
    it("mkdir_p", function()
        local dir = vim.fs.joinpath(tempdir, "bar", "baz", "bat")
        fs.mkdir_p(dir)
        assert.is_not_nil(vim.uv.fs_stat(dir))
    end)
end)
